Аватарки и фото на стороне сервере | Перепись с GD на ImageMagick
everypony/tabun pull request #169
Opened 2021-04-02 22:32 UTC by Ponywka

Файл `./engine/lib/external/LiveImage/Image.php` был переписан на ImageMagick за исключением неиспользующихся в коде функций (закомментированы)

В файле `./classes/actions/ActionSettings.class.php`:
* Функции `EventUploadFoto` и `EventResizeFoto` сокращены до одной `EventUploadFoto`
* Функции `EventUploadAvatar` и `EventResizeAvatar` сокращены до одной `EventUploadAvatar`

Исправление для https://github.com/everypony/tabun/issues/115

2021-04-05 12:13 UTC, KarelWintersky commented
Класс `Imagic()` точно не требует никаких добавлений в `composer.json` ?

2021-04-05 12:20 UTC, roman901 commented
> Класс `Imagic()` точно не требует никаких добавлений в `composer.json` ?

Нет, это библиотека, а не пакет

2021-04-05 15:13 UTC, KarelWintersky commented
Библиотека, которая php-extension :)

Которая требует установки, то есть это надо упоминать в README. ;-)

Я надеюсь, перед разработкой смотрели сюда?

https://packagist.org/packages/orbitale/imagemagick-php
https://packagist.org/packages/calcinai/php-imagick
https://packagist.org/packages/flyimg/flyimg

? :)

2021-04-05 15:38 UTC, roman901 commented
Эм, https://www.php.net/manual/ru/book.imagick.php
Это расширение, да, но композер то тут причём

2021-07-15 11:25 UTC, VozdyxDev commented
Я правильно понимаю, что загрузки аватаров мы не дождёмся?)

2021-07-15 11:28 UTC, KarelWintersky commented
@VozdyxDev , держу пари, сломалась еще и Content Security Policy. Но в общем, я бы не стал ждать.

2021-11-25 18:29 UTC, Orhideous commented
Okay, finally got hands over this one. In light of past and recent vulnerabilities that plagued almost any aspect of user-supplied data in PHP (some of them indeed caused RCE in tabun) discussing prevention of DoS (and, worse, server-side code execution) will be crucial thing to do.

2021-11-25 18:48 UTC, Orhideous requested changes

2021-11-25 18:48 UTC, Orhideous commented on engine/lib/external/LiveImage/Image.php
>  	public function watermark($text, $position=array(0,24), $font_color=array(255, 255, 255), $bg_color=array(0,0,0), $font_alpha=0, $bg_alfa=40 ){
Maybe, delete this alltogether later? In a decade no one bothered about watermarks.

2021-11-25 18:48 UTC, Orhideous commented on classes/actions/ActionSettings.class.php
> +        $filefoto = base64_decode($_POST["image"]);
If anyone (e.g. malicious user) supplies invalid base64 data, then function without strict mode will not fail, despite it should.
Looks like that enabling [strict mode](https://www.php.net/manual/en/function.base64-decode.php) and early quit in case of error would be reasonable precaution.

2021-11-25 18:48 UTC, Orhideous commented on classes/actions/ActionSettings.class.php
> +        file_put_contents($sFile, $filefoto);
`file_put_contents` can [return `false`](https://www.php.net/manual/en/function.file-put-contents.php#refsect1-function.file-put-contents-returnvalues) in case of failure. If we don't have file laying around on disk, then further steps have no sense.

2021-11-25 18:48 UTC, Orhideous commented on classes/actions/ActionSettings.class.php
> +        $fileavatar = base64_decode($_POST["image"]);
See previous comments.

2021-11-25 18:48 UTC, Orhideous commented on engine/lib/external/LiveImage/Image.php
> +			echo $this->image->getImageBlob();
Maybe, log it somehow?

2021-11-25 18:48 UTC, Orhideous commented on engine/lib/external/LiveImage/Image.php
> +			file_put_contents($file, $this->image->getImageBlob());
Same precaution as mentioned earlier

2021-11-27 22:53 UTC, Ponywka commented
Изначально хотел создать ветку `feature/avatars` и обновить PR на неё, но внезапно лёг GitHub, и в итоге забыл это сделать.
Данные изменения уже есть тут: https://github.com/everypony/tabun/tree/feature/avatars, поэтому закрываю этот PR

2021-11-27 22:53 UTC, closed without merging

2021-11-27 22:57 UTC, Orhideous commented
@Ponywka Ok, got it. Will wait for PR! :)