Feature/avatars
everypony/tabun pull request #182
Opened 2021-11-29 22:29 UTC by Ponywka

2021-11-30 09:23 UTC, Orhideous requested changes
Awesome! Many thanks for your work. Would you mean to look on some minor changes?

2021-11-30 09:23 UTC, Orhideous commented on settings/application.php
> +$config['view']['processing']['img_max_height'] = 1000;      // максимальная высота обрабатываемых изображений в пикселях
It's safe to raise this limit to, say, 2048 by default.

2021-11-30 09:23 UTC, Orhideous commented on engine/lib/external/LiveImage/Image.php
> +				$this->image->setFormat("png");
In earlier commit webp support has been added, but it missed there.

2021-11-30 09:23 UTC, Orhideous commented on engine/lib/external/LiveImage/Image.php
> +    ];
This code repeats itself later in different files.

2021-11-30 09:23 UTC, Orhideous commented on classes/modules/user/User.class.php
>              @unlink($sFileTmp);
It's bit out of context, but better to handle those errors explicitly.

2021-11-30 09:23 UTC, Orhideous commented on classes/actions/ActionSettings.class.php
> +                        $this->User_DeleteAvatar($this->oUserCurrent);
Some of this code repeats itself in lines 103-105.

2021-11-30 09:23 UTC, Orhideous commented on classes/modules/user/User.class.php
> +        if ($sFileAvatar=$this->Image_Resize($sFileTmp, $sPath, 'avatar_100x100', $img_max_width, $img_max_height, 100, 100, false)) {
_(not important) Interesting. This code implicitly implies that 100×100 is default avatar size…_

2021-11-30 11:42 UTC, Ponywka commented on classes/modules/user/User.class.php
>              @unlink($sFileTmp);
Окей, что-нибудь придумаем

2021-11-30 11:46 UTC, Orhideous commented on classes/modules/user/User.class.php
>              @unlink($sFileTmp);
Right now it's not a big concern. The worst thing that can happen is that files will remain on the disk due to some FS problem. I guess we can ignore it for now.

2021-11-30 22:23 UTC, Ponywka commented on classes/modules/user/User.class.php
> +        if ($sFileAvatar=$this->Image_Resize($sFileTmp, $sPath, 'avatar_100x100', $img_max_width, $img_max_height, 100, 100, false)) {
Сейчас просмотрел эту строку. Как оказалось она нужна чтобы просто проверить возможность записи в эту папку... А потом по этому же пути аватарка с этим же разрешением создается снова, ибо в конфиге в параметре `module.user.avatar_size` и так есть размер 100x100 :facehoof:

2021-12-01 09:59 UTC, Orhideous approved these changes
LGTM

2021-12-01 09:59 UTC, merged